import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sundowner_plotting import read_file


singleDay_df = read_file("wxobs20250213.txt")
singleDay_df.plot(y= ['Hi_Temp', 'Low_Temp', 'Temp_Out', 'Heat_Index', 'Wind_Chill'],
    figsize=(9, 4),
    title='February 13th, 2025 Temperature Time Series',
    ylabel='Temperature (°F)',
    grid=True,
    alpha=0.7
)
plt.savefig("tempplot02132025.png", dpi=200, bbox_inches = 'tight')
plt.tight_layout()
plt.show()

# print(f"{singleDay_df.columns.values.tolist()}")
days = ["01","02","03","04","05","06","07","08","09",
    "10","11","12","13","14","15","16","17","18","19",
    "20","21","22","23","24","25","26","27","28"]

daily_stats = np.zeros((5,len(days)))
# daily_winds = np.zeros((24*len(days),2))
for i in range(1,29):
    file_name = "wxobs202502" + days[i-1] + ".txt"
    dTime_idx = "2025-02-"+days[i-1] #generates the date time index needed to access the right data point from the pandas series generated by resampling
    # print(f"{file_name}")
    february2025_df = read_file(file_name)
    # print(f"{february2025_df['Wind_Speed'].resample('1h').mean()[dTime_idx]}")
    daily_stats[0,i-1] = february2025_df['Hi_Temp'].resample('1D').max()[dTime_idx]
    daily_stats[1,i-1] = february2025_df['Low_Temp'].resample('1D').min()[dTime_idx]
    daily_stats[2,i-1] = february2025_df['Temp_Out'].resample('1D').max()[dTime_idx]
    daily_stats[3,i-1] = february2025_df['Heat_Index'].resample('1D').mean()[dTime_idx]
    daily_stats[4,i-1] = february2025_df['Wind_Chill'].resample('1D').mean()[dTime_idx]
    # daily_winds[range((i-1)*24,i*24),0] = february2025_df['Wind_Speed'].resample('1h').mean()[dTime_idx]
    


#print(f"{daily_stats}")

fig,ax = plt.subplots()
ax.plot(days, daily_stats.transpose(),alpha=0.7)
plt.title('February 2025 Temperature Time Series')
plt.xticks(rotation=45)
plt.xlabel('Day of the Month')
plt.ylabel('Temperature (°F)')
ax.grid(True,alpha=0.3)
ax.legend(labels=['High Temp', 'Low Temp', 'Temp Out', 'Avg. Heat Index', 'Avg. Wind Chill'],bbox_to_anchor=(1.05, 1))
ax.fill_between(days,daily_stats[3,:], daily_stats[0,:], where=(daily_stats[0,:] > daily_stats[3,:]), color='lightcoral',alpha=0.2)
ax.fill_between(days,daily_stats[3,:], daily_stats[1,:], where=(daily_stats[1,:] < daily_stats[3,:]), color='lightskyblue',alpha=0.2)
plt.savefig("February-2025-Daily-Temperature-Plot.png",bbox_inches='tight',dpi=250)
plt.show()

# fig = plt.figure()
# plt.plot(daily_winds)
# plt.savefig("February-2025-Hourly-Wind-Plot.png",bbox_inches='tight',dpi=250)
# plt.show()