import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sundowner_plotting import read_file


singleDay_df = read_file("wxobs20250213.txt")
singleDay_df.plot(y= ['Hi_Temp', 'Low_Temp', 'Temp_Out', 'Heat_Index', 'Wind_Chill'],
    figsize=(9, 4),
    title='February 13th, 2025 Temperature Time Series',
    ylabel='Temperature (°F)',
    grid=True,
    alpha=0.7
)
plt.savefig("tempplot02132025.png", dpi=200, bbox_inches = 'tight')
plt.tight_layout()
plt.show()

# print(f"{singleDay_df.columns.values.tolist()}")
days = ["01","02","03","04","05","06","07","08","09",
    "10","11","12","13","14","15","16","17","18","19",
    "20","21","22","23","24","25","26","27","28"]

daily_stats = np.zeros((5,len(days)))
for i in range(1,29):
    file_name = "wxobs202502" + days[i-1] + ".txt"
    dTime_idx = "2025-02-"+days[i-1] #generates the date time index needed to access the right data point from the pandas series generated by resampling
    # print(f"{file_name}")
    february2025_df = read_file(file_name)
    # print(f"{february2025_df['Hi_Temp'].resample('1D').max()[dTime_idx]}")
    daily_stats[0,i-1] = february2025_df['Hi_Temp'].resample('1D').max()[dTime_idx]
    daily_stats[1,i-1] = february2025_df['Low_Temp'].resample('1D').max()[dTime_idx]
    daily_stats[2,i-1] = february2025_df['Temp_Out'].resample('1D').max()[dTime_idx]
    daily_stats[3,i-1] = february2025_df['Heat_Index'].resample('1D').max()[dTime_idx]
    daily_stats[4,i-1] = february2025_df['Wind_Chill'].resample('1D').max()[dTime_idx]

#print(f"{daily_stats}")

fig = plt.figure()
plt.plot(days, daily_stats.transpose(),alpha=0.7)
plt.title('February 2025 Temperature Time Series')
plt.xticks(rotation=45)
plt.xlabel('Day of the Month')
plt.ylabel('Temperature (°F)')
plt.grid(True,alpha=0.3)
plt.legend(labels=['Hi_Temp', 'Low_Temp', 'Temp_Out', 'Heat_Index', 'Wind_Chill'],bbox_to_anchor=(1.05, 1))
plt.savefig("February-2025-Daily-Temperature-Plot.png",bbox_inches='tight',dpi=250)
plt.show()

     




# plan:
    # first: consider what kinds of data we want
        # idea 1: accumulation of precip
            # pros: could generate cool graphs
            # cons: requires so much data 
        # idea 2: look at special days, like feb 13th or something
            # pros: less data, unless if comparing across years
            # cons: a little bit more creativity in graphing required
        # idea 3: other accumulations
            # best paired with idea 1, potentially multiple graphs across different variables
            # pros: more even cooler graphs
            # cons: a LOT of data
    # second: import - done!
    # third: refactor - done!
    # four: identify path - done!
        # test grabbing data - pathway found!
    # fifth: test loading text files - done!